PetStagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PetStagram', views.IndexListView.as_view() , name='PetStagram'),
    path('', views.IndexListView.as_view() , name='PetStagram'),
    path('', include('User.urls')),
    path('petStagram/', include('posts.urls')),
]



#Configutation for to load img


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from .views import ProfileCreateView, ProfileLogin, logout_view, UserProfileListView, create_follower, UpdateProfileView, FollowProfileListView

app_name = 'profile'
urlpatterns = [
    path('sing_up', ProfileCreateView.as_view(), name='sing_up'),
    path('login', ProfileLogin.as_view(), name='login'),
    path('update/<slug:slug>', UpdateProfileView.as_view(), name='update'),
    path('logout', logout_view , name='logout'),
    path('<str:username>/slug=<slug:slug>', FollowProfileListView.as_view() , name='follow_profile'),
    path('user', UserProfileListView.as_view() , name='user'),
    path('add_follow', create_follower , name='add_follow'),
]

User/models.py
import random
import string

from django.db import models
from django.utils.text import slugify

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.shortcuts import redirect
from django.urls import reverse

# Create your models here.
def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(10))

class MyUserManager(BaseUserManager):

    def create_user(self , email, password=None):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email)
        )

        user.password = self.set_password(password)
        
        user.save(using=self._db)
        
        return user 
   
class Profile(AbstractUser):
    #We need created a User, based on AbstractUser, but with the anothers functions. 
    biography = models.TextField( blank=True, null=True)
    picture = models.ImageField( upload_to='profiles_pictures', blank=True, null=True)
    email = models.EmailField(max_length=254, unique=True , blank=False , null=False)
    follow = models.ManyToManyField("self", verbose_name=("follow"), related_name="follow", blank=True, null=True)
    slug = models.SlugField(
                    max_length=100, 
                    unique=True , 
                    blank=True
                    )

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.username 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.username + slugify(rand_slug()) 
        super(Profile, self).save( *args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('PetStagram')
    

FOLLOW_CHOICES = (
    ('Follow', 'Follow'),
    ('Unfollow', 'Unfollow')
)   

class UserFollowings(models.Model):
    user_id = models.ForeignKey(Profile , related_name='following', on_delete=models.CASCADE)#user log
    following_user_id = models.ForeignKey(Profile , on_delete=models.CASCADE , related_name='followers')#user to follow
    value = models.CharField(choices = FOLLOW_CHOICES , max_length=10 , default='Follow')
    created_at = models.DateTimeField(auto_now_add=True) 

    class Meta:
        ordering = ["-created_at"]
    
    def __str__(self):
        return f"{self.user_id} follows {self.following_user_id}"

User/forms.py
#import django 
from django.forms import ModelForm

#import the model
from .models import Profile


class ProfileLoginForm(ModelForm):
    class Meta:
        model = Profile
        fields = ("email", "username" , "password" )
    
    def save(self , commit=True ):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

User/views.py
# imports from django 
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import FormView, ListView
from django.views.generic.edit import UpdateView

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect


#Import same app
from .models import Profile, UserFollowings
from .forms import ProfileLoginForm

# imports broad 
from posts.models import UserPost

# Create your views here.

class ProfileCreateView(FormView):
    
    template_name = "profile/sing_up.html"
    form_class = ProfileLoginForm
    success_url = reverse_lazy('PetStagram')

    def form_valid(self, form):
        form.save()
        email = self.request.POST['email']
        password = self.request.POST['password']
        #authenticate user then login
        user = authenticate(email=email, password=password)
        login(self.request, user)
        

        return HttpResponseRedirect(self.get_success_url())
    
    def get_context_data(self ,  **kwargs):
        context = super().get_context_data(**kwargs)
        context['phrase'] = "Sing up to see photos and videos from your friends"
        context['value'] = "Sing Up"
        return context   
class ProfileLogin(LoginView):
    
    # form_class = LoginForm
    template_name = 'profile/login.html'

    def get_context_data(self ,  **kwargs):
        context = super().get_context_data(**kwargs)

        context['phrase'] = "Welcome!"
        context['value'] = "Login"
        return context
class UpdateProfileView(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Profile
    template_name = 'profile/complete_profile.html'
    fields  = ['picture', 'biography']

    def get_context_data(self ,  **kwargs):
        context = super().get_context_data(**kwargs)
        context['phrase'] = "Complete your profile"
        context['value'] = "Complete"
        return context

def logout_view(request):
    logout(request)
    return redirect('/login')
class UserProfileListView(LoginRequiredMixin , ListView):
    login_url = '/login'
    context_object_name = 'user_post'
    model = UserPost
    template_name = 'profile/user_profile.html'
    ordering = '-created_at'

    def get_queryset(self):
        user = self.request.user
        qs = self.model.objects.filter(user=user).all()
        return qs

    def get_context_data(self , **kwargs):
        #we get teh contenxt
        #then create a new value
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

def create_follower(request):
    user = request.user
    if request.method == 'POST':
        user = request.user
        user_id = request.POST.get('following_user_id')
        follow_id = Profile.objects.get(id=user_id)

        if user in follow_id.follow.all():
            follow_id.follow.remove(user)
        else:
            follow_id.follow.add(user)

        follow, created = UserFollowings.objects.get_or_create(user_id=user, following_user_id=follow_id)
        if not created:
            if follow.value == 'Follow':
                follow.value = 'Unfollow'
            else:
                follow.value = 'Follow'

        follow.save()

    return redirect('PetStagram')
class FollowProfileListView(LoginRequiredMixin , ListView):
    login_url = '/login'
    model = UserPost
    template_name = 'follow_profile.html'
    ordering = '-created_at'
    context_object_name = 'user_post'

    def get_queryset(self):
        slug = self.kwargs['slug']
        user = Profile.objects.get(slug=slug)
        post_user = self.model.objects.filter(user=user).all()
        return post_user

    def get_context_data(self , **kwargs):
        #we get teh contenxt
        #then create a new value
        context = super().get_context_data(**kwargs)
        slug = self.kwargs['slug']
        user = Profile.objects.get(slug=slug) 
        context['user'] = user      
        return context

User/templates/profile/complete_profile.html
{% extends 'layout.html' %}

{% load static  %}

{% block container %}


        <div class="sticky-top">
            {% include 'nav_bar.html' %}
        </div>

        <div class="container container-index center-elements mt-5">
            <div class="row center-elements">
                <div class="col wo-p profile_complete center-elements my-5">
                    <img src="{% static 'img/login/user.jpg' %}" alt="img-user" id="img_complete" class='hidden'> 
                </div>
                <div>
                    {% include 'form.html' %}
                </div>
            </div>      
        </div>
{% endblock container %}

User/templates/profile/lay_sing.html
{% extends 'layout.html' %} 
{% load static %} 


{% block container %} 

<div class="container mt-5 ">
    <div class="col-row">
        <div class="col gutters center-elements">
            <img src="{% static 'img/login/mockup.png' %}" alt="" class='img-mockup'>
        </div>

        <div class="col gutters form-elements center-elements ">
            <div class="all">
                <div class="col shadow-sm bg-body rounded form-log py-3 px-3 mt-2 center-elements ">
                    <img src="{% static 'img/login/logo.png' %}" alt="" class='img-logo'>
                    <p class="text-muted text-center">
                        {{phrase}}
                    </p>

                    <input type="submit" value="Sing Up with Facebook" class="btn btn-primary button"/>
                    <hr>
                    {% block form_login %}
                        {% include 'form.html' %}
                    {% endblock form_login %}
                </div>
                
                <div class="col shadow-sm bg-body rounded form-log py-3 px-3 mt-2">
                    Don't have an account? <a href="{% url 'profile:sing_up' %}">Sing Up</a>
                </div>
               
            </div>
        </div>
    </div>
</div>
   h2
{% endblock container %}

User/templates/profile/login.html
{% load static %} 


{% include 'profile/lay_sing.html' %}

User/templates/profile/sing_up.html
{% load static %} 


{% include 'profile/lay_sing.html' %}

User/templates/profile/user_profile.html
{% extends 'layout.html' %}

{% load static  %}

{% block container %}

        <div class="sticky-top">
            {% include 'nav_bar.html' %}
        </div>

        <div class="container container-index ">
            <div class="row">
                <div class="col wo-p">
                    {% include 'userProfile.html' %}
                </div>
            </div>      
        </div>
    
{% endblock container %}