PetStagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PetStagram', views.IndexListView.as_view() , name='PetStagram'),
    path('', views.IndexListView.as_view() , name='PetStagram'),
    path('', include('User.urls')),
    path('petStagram/', include('posts.urls')),
]



#Configutation for to load img


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path

from .views import ProfileCreateView, ProfileLogin, logout_view, UserProfileListView, create_follower, UpdateProfileView, FollowProfileListView

app_name = 'profile'
urlpatterns = [
    path('sing_up', ProfileCreateView.as_view(), name='sing_up'),
    path('login', ProfileLogin.as_view(), name='login'),
    path('update/<slug:slug>', UpdateProfileView.as_view(), name='update'),
    path('logout', logout_view , name='logout'),
    path('<str:username>/slug=<slug:slug>', FollowProfileListView.as_view() , name='follow_profile'),
    path('user', UserProfileListView.as_view() , name='user'),
    path('add_follow', create_follower , name='add_follow'),
]

posts/urls.py
from django.urls import path

from .views import PostDetailView, AddPost, like_post, UpdatePostView, delete_post



app_name = 'post'
urlpatterns = [
    path('add_post', AddPost.as_view(), name='add_post'),
    path('post/<str:slug>', PostDetailView.as_view(), name='post'),
    path('like_post', like_post, name='like_post'),
    path('update/<str:slug>', UpdatePostView.as_view(), name='update'),
    path('delete/<str:slug>', delete_post, name='delete'),
]

templates/feed.html
{% load static  %}


{% for post in posts %}

<div class="light shadow p-3 mb-5 bg-body rounded mt-5 wo-p">

    <div class="col ps-5 center-elements letf-elements py-3 ">
            <a href="{% url 'profile:follow_profile' post.user.username post.user.slug %}" class="img-user">
            {% if post.user.picture.url %}
                <img src="{{ post.user.picture.url }}" alt="" > 
            {% endif %}
            </a>
            <div class="direct-user"> <a href="{% url 'profile:follow_profile' post.user.username post.user.slug %}" class="">{{post.user.username}}</a></div>
            

            {% if request.user != post.user %}
                <form action="{% url 'profile:add_follow' %}" method="POST" class="follow-btn me-3">
                    {% csrf_token %}
                    
                    {% if post.user not in user.follow.all %}
                        <button type="submit" name="following_user_id" value="{{post.user.id}}" class=" btn btn-primary">Unfollow</button>
                    {% else %}
                        <button type="submit" name="following_user_id" value="{{post.user.id}}" class=" btn btn-outline-primary">Follow</button>
                    {% endif %}    
                </form>
            {% else %}
                <div class="dropdown acction-post">
                    <button class="dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-three-dots"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'post:update' post.slug %}">Update</a></li>
                        <li><a class="dropdown-item" href="{% url 'post:delete' post.slug %}">Delete</a></li>
                    </ul>
                </div>
                
            {% endif %}

            
</form>                             
    </div>

    <div class="col img-user-post">
        {% if post.user.picture.url %}      
            <a href="{% url 'post:post' post.slug %}">
                <img src="{{ post.picture.url }}" >
            </a>
        {% endif %}
    </div>
    <div class="col ps-5 py-3 post-icon div-row ">
        
        <form action="{% url 'post:like_post' %}" method="POST" class="me-3">
            {% csrf_token %}
            {% if user not in post.liked.all %}
                <button type="submit" name="post_id" value="{{post.id}}" class="like"><i class="bi bi-heart"></i></button>
            {% else %}
                <button type="submit" name="post_id" value="{{post.id}}" class="like"><i class="bi bi-heart-fill"></i></button>
            {% endif %}
        </form>
        {% if  post.liked.all.count > 0 %}
        <p class="me-3"><strong>{{post.liked.all.count}}</strong>  Likes</p>
           
        {% endif %}

        <i class="bi bi-chat me-3"></i>
    </div>
    <div class="post-description px-5">
        <p><span class="fw-bolder">{{post.user.username}}</span> {{post.description}}</p>
        <p class="text-muted post-date" > {{post.created_at | date:"d F" }} </p>
    </div>
    <hr class="my-2">
    <div class="py-4">
        <form>
            <div class="comments px-5 py3">
            <input type="text"  id="id_comment" placeholder="Add a comments">
            <button type="submit" class="">Submit</button>
            </div>
        </form>
    </div>

</div>
{% endfor %}

templates/index.html
{% extends 'layout.html' %}

{% load static  %}

{% block container %}

        <div class="sticky-top">
            {% include 'nav_bar.html' %}
        </div>

        <div class="container container-index ">
            <div class="row">
                
                <div class="col-8 wo-p">
                    {% include 'feed.html'%}
                </div>

                <div>
                    {% include 'later_bar.html' %}
                </div>
            </div>      
        </div>
    
{% endblock container %}

templates/later_bar.html
{% load static  %}

<div class="col-4 nav-side  mt-5 sticky">
    <div class="col ps-5 center-elements letf-elements py-3 user-side">
     {% if request.user.is_authenticated %}
        {% if request.user.picture.url %}
            <a href="{% url 'profile:user' %}" class="img-user ">
                <img src="{{ request.user.picture.url }}" >
            </a>
        {% endif %}
        <div class="">
            <a href="{% url 'profile:user' %}" class="direct-user fw-bolder">{{request.user.username}}</a>                               
            <a href="{% url 'profile:user' %}" class="direct-user text-muted ">{{request.user.first_name}}</a>                                                    
        </div>
    {% endif %}
    </div>   
</div>

templates/layout.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container-fluid">
        {% block container %}
        
        {% endblock container %}
    </div>

</body>
<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="{%static 'js/bundle.min.js'%}"></script>
</html>

templates/nav_bar.html
{% load static  %}
<nav class="navbar navbar-expand-lg navbar-light bg-light ">
    <div class="container container-index">
            <div class="col-2">
                <a href="/">
                    <img src="{% static 'img/login/logo.png' %}" alt="" class="logo-nav">
                </a>
                    
            </div>

            <div class="col-5">
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> 
            </div>

            <div class="col-5">
                <ul class=" center-elements icon-navbar">
                    <li>
                        <i class="bi bi-house-door-fill"></i>
                    </li>
                    <li>
                        <a href="{% url 'post:add_post' %}"><i class="bi bi-plus-circle"></i></a>
                    </li>
                
                    <li>
                        <i class="bi bi-heart"></i>
                    </li>
                    
                    <li>
                        <i class="bi bi-circle"></i>
                    </li>
                    <li>
                        <a href="{% url 'profile:logout' %}"><i class="bi bi-box-arrow-right"></i></a>
                    </li>
                </ul>
            </div>
    </div>
</nav>   